In [1]:
import pandas as pd
import numpy as np

In [2]:
# Fetch the data

churn_data_raw = pd.read_csv('./raw_data/Churn_Modelling.csv')
churn_data_raw.head(20)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0
5,6,15574012,Chu,645,Spain,Male,44,8,113755.78,2,1,0,149756.71,1
6,7,15592531,Bartlett,822,France,Male,50,7,0.00,2,1,1,10062.80,0
7,8,15656148,Obinna,376,Germany,Female,29,4,115046.74,4,1,0,119346.88,1
8,9,15792365,He,501,France,Male,44,4,142051.07,2,0,1,74940.50,0
9,10,15592389,H?,684,France,Male,27,2,134603.88,1,1,1,71725.73,0
10,11,15767821,Bearce,528,France,Male,31,6,102016.72,2,0,0,80181.12,0
11,12,15737173,Andrews,497,Spain,Male,24,3,0.00,2,1,0,76390.01,0
12,13,15632264,Kay,476,France,Female,34,10,0.00,2,1,0,26260.98,0
13,14,15691483,Chin,549,France,Female,25,5,0.00,2,0,0,190857.79,0
14,15,15600882,Scott,635,Spain,Female,35,7,0.00,2,1,1,65951.65,0
15,16,15643966,Goforth,616,Germany,Male,45,3,143129.41,2,0,1,64327.26,0
16,17,15737452,Romeo,653,Germany,Male,58,1,132602.88,1,1,0,5097.67,1
17,18,15788218,Henderson,549,Spain,Female,24,9,0.00,2,1,1,14406.41,0
18,19,15661507,Muldrow,587,Spain,Male,45,6,0.00,1,0,0,158684.81,0
19,20,15568982,Hao,726,France,Female,24,6,0.00,2,1,1,54724.03,0

In [3]:
churn_data_raw.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [5]:
churn_data = churn_data_raw.drop(columns=['RowNumber','CustomerId','Surname','Gender'])
churn_data.head()

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,41,1,83807.86,1,0,1,112542.58,0
2,502,France,42,8,159660.80,3,1,0,113931.57,1
3,699,France,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,43,2,125510.82,1,1,1,79084.10,0

create a Loyalty feature that represents the percentage of each customer's life that they were customers.

In [6]:
churn_data['Loyalty'] = round(churn_data['Tenure'] / churn_data['Age'],4)
churn_data.head()

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Loyalty
0,619,France,42,2,0.00,1,1,1,101348.88,1,0.0476
1,608,Spain,41,1,83807.86,1,0,1,112542.58,0,0.0244
2,502,France,42,8,159660.80,3,1,0,113931.57,1,0.1905
3,699,France,39,1,0.00,2,0,0,93826.63,0,0.0256
4,850,Spain,43,2,125510.82,1,1,1,79084.10,0,0.0465

In [7]:
churn_data.sort_values(by= 'Loyalty',ascending=False)

,CreditScore,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Loyalty
1619,656,France,18,10,151762.74,1,0,1,127014.32,0,0.5556
4716,646,France,18,10,0.00,2,0,1,52795.15,0,0.5556
8645,636,France,20,10,124266.86,1,0,0,100566.81,0,0.5000
7722,684,Germany,18,9,90544.00,1,0,1,4777.23,0,0.5000
9888,637,France,21,10,125712.20,1,0,0,175072.47,0,0.4762
...,...,...,...,...,...,...,...,...,...,...,...
6734,619,France,55,0,0.00,3,0,0,60810.64,1,0.0000
6590,696,Spain,30,0,0.00,2,1,1,9002.80,0,0.0000
3614,558,Germany,36,0,126606.63,2,1,1,172363.52,0,0.0000
3596,643,France,36,0,148159.71,1,0,0,55835.66,0,0.0000
35,475,France,45,0,134264.04,1,1,0,27822.99,1,0.0000

In [8]:
churn_data['Geography'].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [14]:
churn_transformed = pd.get_dummies(churn_data,drop_first=True,dtype=int)
churn_transformed.head(10)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Loyalty,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1,0.0476,0,0
1,608,41,1,83807.86,1,0,1,112542.58,0,0.0244,0,1
2,502,42,8,159660.80,3,1,0,113931.57,1,0.1905,0,0
3,699,39,1,0.00,2,0,0,93826.63,0,0.0256,0,0
4,850,43,2,125510.82,1,1,1,79084.10,0,0.0465,0,1
5,645,44,8,113755.78,2,1,0,149756.71,1,0.1818,0,1
6,822,50,7,0.00,2,1,1,10062.80,0,0.1400,0,0
7,376,29,4,115046.74,4,1,0,119346.88,1,0.1379,1,0
8,501,44,4,142051.07,2,0,1,74940.50,0,0.0909,0,0
9,684,27,2,134603.88,1,1,1,71725.73,0,0.0741,0,0

In [11]:
churn_transformed = pd.get_dummies(churn_data,drop_first=True) # If there is specification of the dtype it will return a bool
churn_transformed.head(10)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Loyalty,Geography_Germany,Geography_Spain
0,619,42,2,0.00,1,1,1,101348.88,1,0.0476,False,False
1,608,41,1,83807.86,1,0,1,112542.58,0,0.0244,False,True
2,502,42,8,159660.80,3,1,0,113931.57,1,0.1905,False,False
3,699,39,1,0.00,2,0,0,93826.63,0,0.0256,False,False
4,850,43,2,125510.82,1,1,1,79084.10,0,0.0465,False,True
5,645,44,8,113755.78,2,1,0,149756.71,1,0.1818,False,True
6,822,50,7,0.00,2,1,1,10062.80,0,0.1400,False,False
7,376,29,4,115046.74,4,1,0,119346.88,1,0.1379,True,False
8,501,44,4,142051.07,2,0,1,74940.50,0,0.0909,False,False
9,684,27,2,134603.88,1,1,1,71725.73,0,0.0741,False,False